name-template: 'v$tag_name'
tag-template: 'v$tag_name'
categories:
  - title: "🚀 Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "fixed"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    labels:
      - "chore"
      - "refactor"
      - "test"
      - "ci"
      - "docs"
      - "perf"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&@`' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
  patch:
    labels:
      - "patch"
  default: patch
template: |

  Comment

  ### Link

  https://www.powershellgallery.com/packages/DETestModule/$tag_name

  ### Changes

  $CHANGES

  ### Deprecated

  None

  ### Removed

  None

  ### Security

  No changes