name: Publish Module

on: [workflow_dispatch] # Trigger manually - later On Release

jobs:

  publish-module:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install and cache PowerShell modules
        uses: potatoqualitee/psmodulecache@v5.1
        with:
          modules-to-cache: Pester, posh-git, platyPS, InvokeBuild, BuildHelpers, MicrosoftTeams
          #updatable: 'true' # If used, must have cache information (i.e. version number for at least one module)

      - name: Install
        run: .\packages\build\install.ps1

      - name: Build
        run: .\packages\build\build.ps1

      - name: Test
        run: .\packages\build\test.ps1

      - name: Sign
        run: .\packages\build\sign.ps1
        env:
          CODESIGN: ${{secrets.CODESIGN}}

      - name: Publish
        run: .\packages\build\publish.ps1
        # This takes the version from the package.json as it can read that without issue
        env:
          NuGetApiKey: ${{secrets.NuGetApiKey}}

      - name: Complete
        run: Write-Output "Module Published"