name: Release

on: [workflow_dispatch] # Trigger manually (later: on Push to Main)

jobs:

  changelog:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          #skip-version-file: "true" # This would omit the output to the Package JSON, we need that though for publishing!
          #version-file: .\package.json # This is default and does not need to be specified
          output-file: "CHANGELOG.md" # We want a changelog to be created for posterity
          skip-commit: "false" # We want a commit to write the Changelog file
          skip-on-empty: "true"

  package:
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    outputs:
      isPreRelease: ${{ steps.package-json-endpoint.outputs.isPreRelease }}

    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.3.37
        id: package-json-endpoint

      - name: Show PreRelease flag as output
        run: |
          Write-Output "PreRelease set to: ${{ steps.package-json-endpoint.outputs.isPreRelease }}"

  publish:
    needs: package
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest
    env:
      PUSHTOKEN: ${{secrets.PUSHTOKEN}}
      POWERSHELLGALLERY_KEY: ${{secrets.POWERSHELLGALLERY_KEY}}
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/src
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create tag for Head
        run: git tag ${{ needs.changelog.outputs.tag }}

      - name: Create Release
        uses: ncipollo/release-action@v1.11.1
        if: ${{ steps.changelog.outputs.skipped == 'false' }}
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          tag_name: ${{ steps.changelog.outputs.tag }}
          release_name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          draft: true
          omitDraftDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          prerelease: ${{ steps.package.outputs.isPreRelease }}
