name: Release

on: [workflow_dispatch] # Trigger manually (later: on Push to Main)

jobs:

  changelog:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          #skip-version-file: "true" # This would omit the output to the Package JSON, we need that though for publishing!
          #version-file: .\package.json # This is default and does not need to be specified
          output-file: "CHANGELOG.md" # We want a changelog to be created for posterity
          skip-commit: "false" # We want a commit to happen before tagging
          skip-on-empty: "true"

  update_release_draft:
    needs: changelog
    permissions:
      contents: write  # for release-drafter/release-drafter to create a github release
      pull-requests: write  # for release-drafter/release-drafter to add label to PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create tag for Head
        run: git tag ${{ needs.changelog.outputs.tag }}

      - name: 'Get current date'
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: 'Create or update Draft Release'
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #TODO Package and Link are custom variables that are currently not picked up by the release-template.yml
          package: "${{ github.event.repository.name }}"
          link: "https://www.powershellgallery.com/packages/${{ github.event.repository.name }}/${{ needs.changelog.outputs.version }}"
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          config-name: release-template.yml
          #disable-autolabeler: true