name: Release

on: [workflow_dispatch] # Trigger manually (later: on Push to Main)

jobs:

  changelog:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.changelog.outputs.version }}
      body: ${{ steps.changelog.outputs.clean_changelog }}
      tag: ${{ steps.changelog.outputs.tag }}
      skipped: ${{ steps.changelog.outputs.skipped }}
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v3
        with:
          github-token: ${{ secrets.github_token }}
          #skip-version-file: "true" # This would omit the output to the Package JSON, we need that though for publishing!
          #version-file: .\package.json # This is default and does not need to be specified
          output-file: "CHANGELOG.md" # We want a changelog to be created for posterity
          skip-commit: "false" # We want a commit to happen before tagging
          skip-on-empty: "true"

  publish:
    needs: changelog
    if: ${{ needs.changelog.outputs.skipped == 'false' }}
    runs-on: ubuntu-latest
    env:
      PUSHTOKEN: ${{secrets.PUSHTOKEN}}
      POWERSHELLGALLERY_KEY: ${{secrets.POWERSHELLGALLERY_KEY}}
    defaults:
      run:
        shell: pwsh
        working-directory: ${{ github.workspace }}/src
    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Create tag for Head
        run: git tag ${{ needs.changelog.outputs.tag }}

      - name: Create Asset to upload to release
        run: |
          Get-ChildItem | Select-Object LastWriteTime, Length, Size, Name
          #Compress-Archive -DestinationPath ${{ github.event.repository.name }}.zip -Path "src/*"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@1e07f4398721186383de40550babbdf2b84acfc5
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ needs.changelog.outputs.tag }}
          body: ${{ needs.changelog.outputs.body }}
          fail_on_unmatched_files: true
          #token: ${{ secrets.GH_PAT }}
          files: ${{ github.event.repository.name }}.zip
